package com.example.model.siswa


data class AlternatifReq (
    val id : Int,
    val nisn :Int,
    val nama : String,
    val pend_agama : Double,
    val pend_pancasila : Double,
    val bahasa_indo : Double,
    val mtk : Double,
    val sejarah_indo : Double,
    val bahasa_ing : Double,
    val seni_budaya : Double,
    val penjas : Double,
    val prakarya_dan_kwh : Double,
    val biologi : Double,
    val fisika : Double,
    val kimia : Double,
    val sosiologi : Double,
    val ekonomi : Double,
    val ket_pend_agama :Double,
    val ket_pend_pancasila : Double,
    val ket_bahasa_indo : Double,
    val ket_matematika : Double,
    val ket_sejarah_indo : Double,
    val ket_bahasa_ing : Double,
    val ket_seni_budaya : Double,
    val ket_penjas : Double,
    val ket_prakarya_dan_kwh : Double,
    val ket_biologi : Double,
    val ket_fisika : Double,
    val ket_kimia : Double,
    val ket_sosiologi : Double,
    val ket_ekonomi : Double,
    val pramuka : Double,
    val olahraga : Double,
    val pmr : Double,
    val sikap_spiritual : Double,
    val sikap_sosial : Double,
    val sakit : Double,
    val izin : Double,
    val tanpa_keterangan : Double,
    val total : Double
)


